### ISSUE TITLE
Hey michalis,

### ISSUE THREAD

**Issue by Nikoloutsos** [michalispap/Threaded-Pizza#1]
Γεια σου Μιχάλη, 
ωραιος κώδικας και comments, αν δεν εχεις θεμα με αυτο θα μπορουσες να ανεβασεις την εργασια με ενα pull request στο [repo](https://github.com/Nikoloutsos/Aueb-projects) και να γίνει και εσυ contributor σε αυτην την προσπαθεια..

Καλη συνέχεια και ευχομαι τα καλυτερα!

**Comment by michalispap** [comment]
Καλησπέρα Κωνσταντίνε,
θα χαιρόμουν πολύ να συνεισφέρω σε αυτό, οπότε έκανα και το pull request (ελπίζω να το έκανα σωστά, δεν είμαι πολύ εξοικειωμένος ακόμα με το git).
Καλό απόγευμα!

**Comment by Nikoloutsos** [comment]
Καλησπέρα Μιχάλη,
ευχαριστώ πολύ για τον χρόνο σου, δες αυτα που σου εγραψα στο pull request σου
Αν εχεις απορίες κανε με add στο https://www.facebook.com/kostas.Nikoloutsos.66

Καλο απόγευμα
